### PR TITLE
Assorted changes

### PR DESCRIPTION
**Pull request by v1ne**
Hi.
I have Hugo running on the Minos theme on my site. Thanks a lot!
Since I made some changes locally, I'd like to contribute back what I think is generic and useful.
What do you think?
I'm fine with dropping some commits if you don't see the value.

### CODE REVIEW

**Comment by carsonip** [comment]
Hi @v1ne, thanks for the great work! Since I am not actively maintaining the project and I have been away from hugo theme development, I am not 100% clear with the changes but they look ok. For the omitDate param, it is possible to document it in the readme? Then this PR is good to go.

**Comment by v1ne** [comment]
@carsonip: Good point! I added a paragraph to the `README.md`

**Comment by carsonip** [comment]
Thanks!

**Comment by carsonip** [comment]
@v1ne please look at #37 and note that we assume `.Site.Params.Author` is a string and how we ignore `.Site.Author`. If `.Site.Author` support is needed, please submit a PR.

**Comment by v1ne** [comment]
@carsonip: :eyes: Hmm, so it's just a string. Ok. I saw that you already fixed it, thanks!
Sorry for causing the trouble. Next time, I'll test against the Themes website, too!

**Pull request merged**
